# Cobro Digital (CoDi)

In [ ]:
from google.colab import drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Lectura de archivos .csv

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
ruta = '/content/drive/MyDrive/Python - Modulo BEDU/Postwork/DATASET'

In [ ]:
una_transaccion = pd.read_csv(f'{ruta}/cuentas_una_transaccion_raw.csv')
cuentas_validas = pd.read_csv(f'{ruta}/cuentas_validas_raw.csv')
smartphones = pd.read_csv(f'{ruta}/dispositivos_enrolados_raw.csv')
monto_procesado = pd.read_csv(f'{ruta}/monto_procesado_raw.csv')
transacciones = pd.read_csv(f'{ruta}/operaciones_realizadas_raw.csv')

In [ ]:
df_una_transaccion = pd.DataFrame(una_transaccion)
df_cuentas_validas = pd.DataFrame(cuentas_validas)
df_smartphones = pd.DataFrame(smartphones)
df_monto_procesado = pd.DataFrame(monto_procesado)
df_transacciones = pd.DataFrame(transacciones)

#Exploración inicial y limpieza de datos 

En esta sección comenzaremos a manipular los dataframes para hacer las limpiezas de los mismos. Y la conversión a los tipos correctos de datos para su posterior manipulación.

### Dataframe cuentas validadas

**cuentas_validas.csv** 

*Descripción:* Cantidad de cuentas diarias válidas por banco que se han registrado el sistema CoDi.

Este dataset consta de 968 renglones y 42 columnas. La primera columna representa la fecha (se toma como indice), la segunda columna contiene “Total de cuentas validadas” y las 40 columnas restantes contienen el número de cuentas validadas por diferentes instituciones bancarias, algunos ejemplos son ABC Capital, S.A., Accendo Banco, S. A., Banco Actinver, S.A.

#### Exploración inicial

In [ ]:
df_cuentas_validas

,Fecha,Total de cuentas validadas,"Cuentas validadas de ABC Capital, S.A.","Cuentas validadas de Accendo Banco, S.A.","Cuentas validadas de Banco Actinver, S.A.","Cuentas validadas de Banca Afirme, S.A.","Cuentas validadas de Opciones Empresariales del Noreste, S.A. de C.V.","Cuentas validadas de Banco Autofin México, S.A.","Cuentas validadas de Banco Azteca, S.A.","Cuentas validadas de Banco del Bajío, S.A.",...,"Cuentas validadas de Banco Invex, S.A.","Cuentas validadas de Banca Mifel, S.A.","Cuentas validadas de Banco Multiva, S.A.","Cuentas validadas de Banco Pagatodo, S.A.","Cuentas validadas de Banco Sabadell, S.A.","Cuentas validadas de Banco Santander (México), S.A.","Cuentas validadas de Scotiabank Inverlat, S.A.","Cuentas validadas de Sistema de Transferencias y Pagos STP, S.A. de C.V.","Cuentas validadas de Operadora de Pagos Móviles de México, S.A de C.V.","Cuentas validadas de Banco Ve Por Mas, S.A."
0,24/05/2020,20477,0,N/E,0,41,5,2,718,21,...,0,5,0,24,0,1084,373,8,0,1
1,25/05/2020,9422,0,N/E,0,11,2,1,294,9,...,0,3,0,8,0,411,143,5,0,0
2,26/05/2020,9494,0,N/E,0,27,2,2,243,4,...,0,4,0,4,1,375,170,6,0,2
3,27/05/2020,11850,0,N/E,0,16,1,0,233,9,...,0,2,0,7,1,359,200,3,0,0
4,28/05/2020,13902,0,N/E,0,16,1,1,297,15,...,0,0,0,17,2,391,270,8,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
963,12/01/2023,11829,0,N/E,0,37,10,1,470,14,...,0,3,0,5,0,289,51,21,0,1
964,13/01/2023,13842,0,N/E,0,44,14,0,297,39,...,0,1,0,6,0,323,35,15,0,0
965,14/01/2023,10920,0,N/E,0,22,1,0,188,26,...,1,1,0,2,0,258,175,10,0,0
966,15/01/2023,9435,1,N/E,0,10,0,0,488,20,...,0,1,0,2,0,210,175,17,0,0
967,16/01/2023,12613,0,N/E,0,22,7,1,251,13,...,0,4,0,1,0,272,21,12,0,0

In [ ]:
df_cuentas_validas.columns
df_cuentas_validas.dtypes
df_cuentas_validas.shape
df_cuentas_validas.head()
df_cuentas_validas.tail()

,Fecha,Total de cuentas validadas,"Cuentas validadas de ABC Capital, S.A.","Cuentas validadas de Accendo Banco, S.A.","Cuentas validadas de Banco Actinver, S.A.","Cuentas validadas de Banca Afirme, S.A.","Cuentas validadas de Opciones Empresariales del Noreste, S.A. de C.V.","Cuentas validadas de Banco Autofin México, S.A.","Cuentas validadas de Banco Azteca, S.A.","Cuentas validadas de Banco del Bajío, S.A.",...,"Cuentas validadas de Banco Invex, S.A.","Cuentas validadas de Banca Mifel, S.A.","Cuentas validadas de Banco Multiva, S.A.","Cuentas validadas de Banco Pagatodo, S.A.","Cuentas validadas de Banco Sabadell, S.A.","Cuentas validadas de Banco Santander (México), S.A.","Cuentas validadas de Scotiabank Inverlat, S.A.","Cuentas validadas de Sistema de Transferencias y Pagos STP, S.A. de C.V.","Cuentas validadas de Operadora de Pagos Móviles de México, S.A de C.V.","Cuentas validadas de Banco Ve Por Mas, S.A."
963,12/01/2023,11829,0,N/E,0,37,10,1,470,14,...,0,3,0,5,0,289,51,21,0,1
964,13/01/2023,13842,0,N/E,0,44,14,0,297,39,...,0,1,0,6,0,323,35,15,0,0
965,14/01/2023,10920,0,N/E,0,22,1,0,188,26,...,1,1,0,2,0,258,175,10,0,0
966,15/01/2023,9435,1,N/E,0,10,0,0,488,20,...,0,1,0,2,0,210,175,17,0,0
967,16/01/2023,12613,0,N/E,0,22,7,1,251,13,...,0,4,0,1,0,272,21,12,0,0

#### Limpieza de datos

In [ ]:
#Convertir a nomenclatura snake_case

df_cuentas_validas.columns=df_cuentas_validas.columns.str.replace("Cuentas validadas de ","")
df_cuentas_validas.columns=df_cuentas_validas.columns.str.replace(", S.A.","")
df_cuentas_validas.columns=df_cuentas_validas.columns.str.replace(" S.A.","")
df_cuentas_validas.columns=df_cuentas_validas.columns.str.replace(" S.A","")
df_cuentas_validas.columns=df_cuentas_validas.columns.str.replace(" de C.V.","")
df_cuentas_validas.columns=df_cuentas_validas.columns.str.replace(" C.V.","")
df_cuentas_validas.columns=df_cuentas_validas.columns.str.replace(", S.N.C.","")
df_cuentas_validas.columns=df_cuentas_validas.columns.str.replace(" ","_")
df_cuentas_validas.columns=df_cuentas_validas.columns.str.lower()

<ipython-input-94-886b35eafa12>:4: FutureWarning: The default value of regex will change from True to False in a future version.
  df_cuentas_validas.columns=df_cuentas_validas.columns.str.replace(", S.A.","")
<ipython-input-94-886b35eafa12>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df_cuentas_validas.columns=df_cuentas_validas.columns.str.replace(" S.A.","")
<ipython-input-94-886b35eafa12>:6: FutureWarning: The default value of regex will change from True to False in a future version.
  df_cuentas_validas.columns=df_cuentas_validas.columns.str.replace(" S.A","")
<ipython-input-94-886b35eafa12>:7: FutureWarning: The default value of regex will change from True to False in a future version.
  df_cuentas_validas.columns=df_cuentas_validas.columns.str.replace(" de C.V.","")
<ipython-input-94-886b35eafa12>:8: FutureWarning: The default value of regex will change from True to False in a future version.
  df_cuentas_validas.columns=df_cuentas_validas.columns.str.replace(" C.V.","")
<ipython-input-94-886b35eafa12>:9: FutureWarning: The default value of regex will change from True to False in a future version.
  df_cuentas_validas.columns=df_cuentas_validas.columns.str.replace(", S.N.C.","")

In [ ]:
#Conversión de datos a tipo númericos.
#Los datos que sean N/E los va a convertir a NaN

df_cuentas_validas.iloc[:,1:] = df_cuentas_validas.iloc[:,1:].applymap(lambda x: pd.to_numeric(x, errors='coerce'))
 
 #Convertimos la columna fecha a formato datetime
df_cuentas_validas['fecha'] = pd.to_datetime(df_cuentas_validas['fecha'], format='%d/%m/%Y')

#Verificación de la conversión de datos

df_cuentas_validas.dtypes

fecha                                                 datetime64[ns]
total_de_cuentas_validadas                                     int64
abc_capital                                                    int64
accendo_banco                                                float64
banco_actinver                                                 int64
banca_afirme                                                   int64
opciones_empresariales_del_noreste                             int64
banco_autofin_méxico                                           int64
banco_azteca                                                   int64
banco_del_bajío                                                int64
banco_nacional_de_méxico                                       int64
banco_ahorro_famsa                                           float64
bancoppel                                                      int64
banco_bancrea                                                  int64
banco_nacional_del_ejército,_fuerza_aérea_y_armada             int64
bankaool                                                       int64
banco_mercantil_del_norte                                      int64
banco_regional                                                 int64
banco_del_ahorro_nacional_y_servicios_financieros              int64
bansi                                                          int64
banco_base                                                     int64
bbva_bancomer                                                  int64
banco_monex                                                    int64
cibanco                                                        int64
banco_compartamos                                              int64
consubanco,                                                    int64
fundación_dondé_banco                                          int64
fincomún,_servicios_financieros_comunitarios                   int64
hsbc_méxico                                                    int64
banco_inbursa                                                  int64
banco_inmobiliario_mexicano                                    int64
intercam_banco                                                 int64
banco_invex                                                    int64
banca_mifel                                                    int64
banco_multiva                                                  int64
banco_pagatodo                                                 int64
banco_sabadell                                                 int64
banco_santander_(méxico)                                       int64
scotiabank_inverlat                                            int64
sistema_de_transferencias_y_pagos_stp                          int64
operadora_de_pagos_móviles_de_méxicode                         int64
banco_ve_por_mas                                               int64
dtype: object

In [ ]:
#Conteo de los valores NaN del dataframe
conteo_nulos_df_cuentas_validas=df_cuentas_validas.isna().sum(axis=0)

bancos_cuentas_validas_nulos = df_cuentas_validas.columns[df_cuentas_validas.isnull().any()].tolist()
print(f"Los bancos que tienen valores nulos son: {bancos_cuentas_validas_nulos}")

Los bancos que tienen valores nulos son: ['accendo_banco', 'banco_ahorro_famsa']

In [ ]:
#Borramos las columnas que tienen valores N/A
df_cuentas_validas= df_cuentas_validas.dropna(axis=1,how='any')

In [ ]:
#Reseteamos el indice y corroboramos el nuevo tamaño del dataframe cuentas_validadas
df_cuentas_validas = df_cuentas_validas.reset_index(drop=True)
df_cuentas_validas.shape

#El tamaño del dataframe original es de 968 filas y 42 columnas
#Después de la limpieza de datos queda de 968 filas y 40 columnas

(968, 40)

### Dataframe una transacción

**cuentas_una_transaccion.csv** 

*Descripción:* Cantidad de cuentas que han realizado al menos una operación CoDi por día.

Este dataset consta de 1182 renglones y 3 columnas. La segunda columna corresponde al número de cuentas que han realizado al menos un pago y la tercera columna corresponde al número de cuentas que han realizado al menos un cobro.

#### Exploración inicial

In [ ]:
df_una_transaccion

,Fecha,Cuentas que han realizado al menos un pago,Cuentas que han realizado al menos un cobro
0,23/10/2019,19089,17717
1,24/10/2019,19706,18257
2,25/10/2019,20905,19383
3,26/10/2019,N/E,N/E
4,27/10/2019,N/E,N/E
...,...,...,...
1177,12/01/2023,1229066,816604
1178,13/01/2023,1231154,817316
1179,14/01/2023,1232536,817836
1180,15/01/2023,1233759,818252
1181,16/01/2023,1235516,818737

In [ ]:
df_una_transaccion.columns
df_una_transaccion.dtypes
df_una_transaccion.shape
df_una_transaccion.head()
df_una_transaccion.tail()

,Fecha,Cuentas que han realizado al menos un pago,Cuentas que han realizado al menos un cobro
1177,12/01/2023,1229066,816604
1178,13/01/2023,1231154,817316
1179,14/01/2023,1232536,817836
1180,15/01/2023,1233759,818252
1181,16/01/2023,1235516,818737

#### Limpieza de datos

In [ ]:
# Cambio de nomenclatura a snake_case
df_una_transaccion.columns = ["fecha","cuentas_que_han_realizado_al_menos_un_pago","cuentas_que_han_realizado_al_menos_un_cobro"]

In [ ]:
#Conversión a tipos de datos numericos, los datos que no se puedan convertir , los convertirá a NaN

df_una_transaccion["cuentas_que_han_realizado_al_menos_un_pago"] = pd.to_numeric(df_una_transaccion["cuentas_que_han_realizado_al_menos_un_pago"], errors='coerce') # Conversion a tipo numerica
df_una_transaccion["cuentas_que_han_realizado_al_menos_un_cobro"] = pd.to_numeric(df_una_transaccion["cuentas_que_han_realizado_al_menos_un_cobro"], errors='coerce') # Conversion a tipo numerica

#Covertimos la columna tipo fecha

df_una_transaccion['fecha'] = pd.to_datetime(df_una_transaccion['fecha'], format='%d/%m/%Y')

#Checamos que la conversion se halla realizado correctamente

df_una_transaccion.dtypes

fecha                                          datetime64[ns]
cuentas_que_han_realizado_al_menos_un_pago            float64
cuentas_que_han_realizado_al_menos_un_cobro           float64
dtype: object

In [ ]:
#Conteo de valores NaN por columna
df_una_transaccion.isna().sum(axis=0)

fecha                                            0
cuentas_que_han_realizado_al_menos_un_pago     175
cuentas_que_han_realizado_al_menos_un_cobro    175
dtype: int64

In [ ]:
#Quitamos las filas que tienen N/A (175 filas)
df_una_transaccion=df_una_transaccion.dropna(how='any')
df_una_transaccion.isna().sum(axis=0)

fecha                                          0
cuentas_que_han_realizado_al_menos_un_pago     0
cuentas_que_han_realizado_al_menos_un_cobro    0
dtype: int64

In [ ]:
#Resetamos los indices por los datos que borramos

df_una_transaccion = df_una_transaccion.reset_index(drop=True)

#Tamaño del dataframe
df_una_transaccion.shape

(1007, 3)

### Dataframe de smartphones

**dispositivos_enrolados.csv** 

*Descripción:* Cantidad de dispositivos enrolados diarios por sistema operativo android o iOS por institución bancaria.

Este dataset consta de 1164 renglones y 85 columnas. La segunda columna corresponde al número total de dispositivos Android enrolados, las siguientes 43 columnas corresponden al número de dispositivos Android enrolados por diferentes instituciones bancarias. La columna 46 contiene el número total de dispositivos iOS enrolados y las siguientes 39 columnas corresponde al número de dispositivos iOS enrolados por diferentes instituciones bancarias.

#### Exploración inicial

In [ ]:
df_smartphones

,Fecha,Total de dispositivos Android enrolados,Dispositivos Android enrolados del Banco de México,Dispositivos Android enrolados de las instituciones financieras,"Dispositivos Android enrolados de Accendo Banco, S.A.","Dispositivos Android enrolados de Banco Actinver, S.A.","Dispositivos Android enrolados de Opciones Empresariales del Noreste, S.A. de C.V.","Dispositivos Android enrolados de Banco Autofin México, S.A.","Dispositivos Android enrolados de Banco Azteca, S.A.","Dispositivos Android enrolados de Banco del Bajío, S.A.",...,"Dispositivos iOS enrolados de Banco Pagatodo, S.A.","Dispositivos iOS enrolados de Banco Sabadell, S.A.","Dispositivos iOS enrolados de Banco Santander (México), S.A.","Dispositivos iOS enrolados de Scotiabank Inverlat, S.A.","Dispositivos iOS enrolados de Sistema de Transferencias y Pagos STP, S.A. de C.V.","Dispositivos iOS enrolados de Operadora de Pagos Móviles de México, S.A. de C.V.","Dispositivos iOS enrolados de Banco Ve Por Mas, S.A.",Dispositivos iOS enrolados de los terceros desarrolladores,"Dispositivos iOS enrolados de Kimerkia, S.A. de C.V.","Dispositivos iOS enrolados de WISECAP, S.A. de C.V."
0,01/11/2019,N/E,N/E,0,N/E,N/E,N/E,N/E,N/E,N/E,...,N/E,N/E,N/E,N/E,N/E,N/E,N/E,N/E,N/E,N/E
1,11/11/2019,837202,39602,797600,N/E,124,327,0,18919,2775,...,199,0,6395,21218,12,1726,227,0,N/E,N/E
2,12/11/2019,852648,39766,812882,N/E,124,329,0,19261,2800,...,206,0,6538,21439,12,1776,229,0,N/E,N/E
3,13/11/2019,869197,39905,829292,N/E,125,330,0,19654,2824,...,211,0,6741,21667,12,1831,230,0,N/E,N/E
4,14/11/2019,885713,40043,845670,N/E,125,332,0,20000,2857,...,214,0,6933,21884,12,1880,232,0,N/E,N/E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1159,12/01/2023,15666699,78075,15588220,N/E,563,4323,1154,463863,35992,...,2486,535,126311,137814,819,79906,796,129,N/E,129
1160,13/01/2023,15679910,78206,15601300,N/E,563,4338,1155,464363,36049,...,2488,535,126468,137955,819,79917,796,129,N/E,129
1161,14/01/2023,15689332,78305,15610623,N/E,564,4339,1155,464544,36086,...,2488,535,126586,138044,820,79930,796,129,N/E,129
1162,15/01/2023,15697810,78420,15618986,N/E,565,4340,1158,465034,36129,...,2488,535,126698,138120,821,79943,797,129,N/E,129
1163,16/01/2023,15709369,78559,15630406,N/E,565,4348,1159,465531,36165,...,2489,535,126823,138243,822,79959,797,129,N/E,129

In [ ]:
df_smartphones.columns
df_smartphones.dtypes
df_smartphones.shape
df_smartphones.head()
df_smartphones.tail()

,Fecha,Total de dispositivos Android enrolados,Dispositivos Android enrolados del Banco de México,Dispositivos Android enrolados de las instituciones financieras,"Dispositivos Android enrolados de Accendo Banco, S.A.","Dispositivos Android enrolados de Banco Actinver, S.A.","Dispositivos Android enrolados de Opciones Empresariales del Noreste, S.A. de C.V.","Dispositivos Android enrolados de Banco Autofin México, S.A.","Dispositivos Android enrolados de Banco Azteca, S.A.","Dispositivos Android enrolados de Banco del Bajío, S.A.",...,"Dispositivos iOS enrolados de Banco Pagatodo, S.A.","Dispositivos iOS enrolados de Banco Sabadell, S.A.","Dispositivos iOS enrolados de Banco Santander (México), S.A.","Dispositivos iOS enrolados de Scotiabank Inverlat, S.A.","Dispositivos iOS enrolados de Sistema de Transferencias y Pagos STP, S.A. de C.V.","Dispositivos iOS enrolados de Operadora de Pagos Móviles de México, S.A. de C.V.","Dispositivos iOS enrolados de Banco Ve Por Mas, S.A.",Dispositivos iOS enrolados de los terceros desarrolladores,"Dispositivos iOS enrolados de Kimerkia, S.A. de C.V.","Dispositivos iOS enrolados de WISECAP, S.A. de C.V."
1159,12/01/2023,15666699,78075,15588220,N/E,563,4323,1154,463863,35992,...,2486,535,126311,137814,819,79906,796,129,N/E,129
1160,13/01/2023,15679910,78206,15601300,N/E,563,4338,1155,464363,36049,...,2488,535,126468,137955,819,79917,796,129,N/E,129
1161,14/01/2023,15689332,78305,15610623,N/E,564,4339,1155,464544,36086,...,2488,535,126586,138044,820,79930,796,129,N/E,129
1162,15/01/2023,15697810,78420,15618986,N/E,565,4340,1158,465034,36129,...,2488,535,126698,138120,821,79943,797,129,N/E,129
1163,16/01/2023,15709369,78559,15630406,N/E,565,4348,1159,465531,36165,...,2489,535,126823,138243,822,79959,797,129,N/E,129

#### Limpieza de datos

In [ ]:
#Cambiando las columnas a nomenclatura snake_case

df_smartphones.columns=df_smartphones.columns.str.replace("Dispositivos Android enrolados de","Android")
df_smartphones.columns=df_smartphones.columns.str.replace("Dispositivos iOS enrolados de","ios")
df_smartphones.columns=df_smartphones.columns.str.replace(", S.A.","")
df_smartphones.columns=df_smartphones.columns.str.replace(" S.A.","")
df_smartphones.columns=df_smartphones.columns.str.replace(" de C.V.","")
df_smartphones.columns=df_smartphones.columns.str.replace(" de R.L.","")
df_smartphones.columns=df_smartphones.columns.str.replace("iosl","ios")
df_smartphones.columns=df_smartphones.columns.str.replace(" ","_")
df_smartphones.columns=df_smartphones.columns.str.replace("androidl ","android")
df_smartphones.columns=df_smartphones.columns.str.lower()

<ipython-input-108-7d30e225f2fe>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df_smartphones.columns=df_smartphones.columns.str.replace(", S.A.","")
<ipython-input-108-7d30e225f2fe>:6: FutureWarning: The default value of regex will change from True to False in a future version.
  df_smartphones.columns=df_smartphones.columns.str.replace(" S.A.","")
<ipython-input-108-7d30e225f2fe>:7: FutureWarning: The default value of regex will change from True to False in a future version.
  df_smartphones.columns=df_smartphones.columns.str.replace(" de C.V.","")
<ipython-input-108-7d30e225f2fe>:8: FutureWarning: The default value of regex will change from True to False in a future version.
  df_smartphones.columns=df_smartphones.columns.str.replace(" de R.L.","")

In [ ]:
#Convertimos los datos a tipo numerico 
#Los valores que no sean del tipo numerico , se convertiran en NaN

for i in range(1,len(df_smartphones.columns)):
    a=smartphones.columns[i]
    df_smartphones[a] = pd.to_numeric(df_smartphones[a], errors='coerce')

#Convertimos la columna de fecha a tipo datetime

df_smartphones['fecha'] = pd.to_datetime(df_smartphones['fecha'], format='%d/%m/%Y')

#Revisamos que la conversion se halla realizado correctamente

df_smartphones.dtypes

fecha                                       datetime64[ns]
total_de_dispositivos_android_enrolados            float64
androidl_banco_de_méxico                           float64
android_las_instituciones_financieras              float64
android_accendo_banco                              float64
                                                 ...
ios_operadora_de_pagos_móviles_de_méxico           float64
ios_banco_ve_por_mas                               float64
ios_los_terceros_desarrolladores                   float64
ios_kimerkia                                       float64
ios_wisecap                                        float64
Length: 85, dtype: object

In [ ]:
#Cantidad de datos N/A

df_smartphones.isna().sum(axis=0)

fecha                                          0
total_de_dispositivos_android_enrolados       66
androidl_banco_de_méxico                      66
android_las_instituciones_financieras         65
android_accendo_banco                       1095
                                            ...
ios_operadora_de_pagos_móviles_de_méxico      66
ios_banco_ve_por_mas                          66
ios_los_terceros_desarrolladores              66
ios_kimerkia                                1123
ios_wisecap                                  670
Length: 85, dtype: int64

In [ ]:
df_smartphones=df_smartphones.dropna(how='all') #Quitamos las filas que todos sus valores son N/A

#Hay algunas filas que no todos sus datos fueron N/A, 
#notamos que el patrón ocurre con 66 filas , que al momento de colocar la informacion en la base de datos , colocaron un 0 en lugar del N/E
df_smartphones.isna().sum(axis=0)

fecha                                          0
total_de_dispositivos_android_enrolados       66
androidl_banco_de_méxico                      66
android_las_instituciones_financieras         65
android_accendo_banco                       1095
                                            ...
ios_operadora_de_pagos_móviles_de_méxico      66
ios_banco_ve_por_mas                          66
ios_los_terceros_desarrolladores              66
ios_kimerkia                                1123
ios_wisecap                                  670
Length: 85, dtype: int64

In [ ]:
df_smartphones.loc[0] # Por ejemplo en la fila 0 , todos los valores son NaN  a exepcion de la columna de android_instituciones_financiera
#Lo más logico es que ese 0.0 sea NaN

fecha                                       2019-11-01 00:00:00
total_de_dispositivos_android_enrolados                     NaN
androidl_banco_de_méxico                                    NaN
android_las_instituciones_financieras                       0.0
android_accendo_banco                                       NaN
                                                   ...
ios_operadora_de_pagos_móviles_de_méxico                    NaN
ios_banco_ve_por_mas                                        NaN
ios_los_terceros_desarrolladores                            NaN
ios_kimerkia                                                NaN
ios_wisecap                                                 NaN
Name: 0, Length: 85, dtype: object

In [ ]:
#Vamos a encontrar las columnas que tengan mas de 66 N/A
columnas_df_smartphones_nulos = df_smartphones.columns[df_smartphones.isnull().sum() > 66]
print(f"Las columnas que tienen valores nulos son: {columnas_df_smartphones_nulos}")

#Procedemos a borrar las columnas que tienen valores nulos
df_smartphones =df_smartphones.drop(columnas_df_smartphones_nulos, axis=1)

#Procedemos a borrar las filas que contengan al menos un valor nulo

df_smartphones=df_smartphones.dropna(how='any')

Las columnas que tienen valores nulos son: Index(['android_accendo_banco', 'android_banco_ahorro_famsa',
       'android_banco_inmobiliario_mexicano', 'android_intercam_banco',
       'android_kimerkia', 'android_quetzalcóatl_sistemas',
       'android_national_soft_de_méxico', 'android_wisecap',
       'ios_banco_ahorro_famsa', 'ios_banco_inmobiliario_mexicano',
       'ios_intercam_banco', 'ios_banco_sabadell', 'ios_kimerkia',
       'ios_wisecap'],
      dtype='object')

In [ ]:
df_smartphones = df_smartphones.reset_index(drop=True)
df_smartphones.shape

#El tamaño del dataframe original es de 1164 filas y 84 columnas
#Después de la limpieza de datos queda de 1098 filas y 71 columnas

(1098, 71)

### Dataframe monto procesado
**monto_procesado.csv **

*Descripción:* Montos totales diarios enviados y recibidos por cada institución bancaria.

Este dataset consta de 1205 renglones y 77 columnas. La segunda columna corresponde al monto total enviado, las siguientes 35 columnas corresponden al monto enviado por diferentes entidades bancarias. La columna 38 corresponde al monto total recibido y las siguientes 39 columnas corresponden al monto recibido por diferentes entidades bancarias.

#### Exploración inicial

In [ ]:

df_monto_procesado

,Fecha,Total de monto enviado,"Monto enviado por Accendo Banco, S.A.","Monto enviado por Banco Actinver, S.A.","Monto enviado por Banca Afirme, S.A.","Monto enviado por Opciones Empresariales del Noreste, S.A. de C.V.","Monto enviado por Banco Autofin México, S.A.","Monto enviado por Banco Azteca, S.A.","Monto enviado por Banco del Bajío, S.A.","Monto enviado por Banco Nacional de México, S.A.",...,"Monto recibido por Intercam Banco, S.A.","Monto recibido por Banco Invex, S.A.","Monto recibido por Banca Mifel, S.A.","Monto recibido por Banco Multiva, S.A.","Monto recibido por Banco Pagatodo, S.A.","Monto recibido por Banco Sabadell, S.A.","Monto recibido por Banco Santander (México), S.A.","Monto recibido por Scotiabank Inverlat, S.A.","Monto recibido por Sistema de Transferencias y Pagos STP, S.A. de C.V.","Monto recibido por Banco Ve Por Mas, S.A."
0,30/09/2019,187009,0,74,16,2222,0,7565,3400,105972,...,140,13,18,0,1167,0,874,5,366,16
1,01/10/2019,311813,0,21,5,0,0,4590,14873,187411,...,325,10,0,0,6994,0,12180,10,363,3
2,02/10/2019,360606,0,0,12,300,0,3662,4466,216259,...,408,20,20,0,6085,0,3146,10,36,206
3,03/10/2019,399780,0,326,1055,17570,0,7679,4699,216406,...,90,0,1,0,6767,0,8392,59,47,25
4,04/10/2019,398796,0,8,1895,9855,0,12468,14519,187362,...,35,0,20,0,796,0,18597,11262,61,281
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1200,12/01/2023,10143818,0,0,36521,0,1,1271398,196230,710139,...,5119,0,22,0,7,0,301356,75409,76329,0
1201,13/01/2023,16181272,0,0,38665,0,1,1665568,1144991,1614709,...,2771,0,9224,0,883,2,503289,123294,484669,0
1202,14/01/2023,8138039,0,1999,18542,0,0,328229,491345,967148,...,4000,600,0,0,1,0,365832,92316,133770,2900
1203,15/01/2023,4425454,0,198,1860,0,0,478913,355231,452224,...,798,0,0,0,2,0,379669,72874,101587,0
1204,16/01/2023,10391490,0,0,37161,0,0,1352385,377173,890585,...,4074,0,4754,0,2,0,257038,129662,1280950,1

In [ ]:
df_monto_procesado.columns
df_monto_procesado.dtypes
df_monto_procesado.shape
df_monto_procesado.head()
df_monto_procesado.tail()

,Fecha,Total de monto enviado,"Monto enviado por Accendo Banco, S.A.","Monto enviado por Banco Actinver, S.A.","Monto enviado por Banca Afirme, S.A.","Monto enviado por Opciones Empresariales del Noreste, S.A. de C.V.","Monto enviado por Banco Autofin México, S.A.","Monto enviado por Banco Azteca, S.A.","Monto enviado por Banco del Bajío, S.A.","Monto enviado por Banco Nacional de México, S.A.",...,"Monto recibido por Intercam Banco, S.A.","Monto recibido por Banco Invex, S.A.","Monto recibido por Banca Mifel, S.A.","Monto recibido por Banco Multiva, S.A.","Monto recibido por Banco Pagatodo, S.A.","Monto recibido por Banco Sabadell, S.A.","Monto recibido por Banco Santander (México), S.A.","Monto recibido por Scotiabank Inverlat, S.A.","Monto recibido por Sistema de Transferencias y Pagos STP, S.A. de C.V.","Monto recibido por Banco Ve Por Mas, S.A."
1200,12/01/2023,10143818,0,0,36521,0,1,1271398,196230,710139,...,5119,0,22,0,7,0,301356,75409,76329,0
1201,13/01/2023,16181272,0,0,38665,0,1,1665568,1144991,1614709,...,2771,0,9224,0,883,2,503289,123294,484669,0
1202,14/01/2023,8138039,0,1999,18542,0,0,328229,491345,967148,...,4000,600,0,0,1,0,365832,92316,133770,2900
1203,15/01/2023,4425454,0,198,1860,0,0,478913,355231,452224,...,798,0,0,0,2,0,379669,72874,101587,0
1204,16/01/2023,10391490,0,0,37161,0,0,1352385,377173,890585,...,4074,0,4754,0,2,0,257038,129662,1280950,1

#### Limpieza de Datos

In [ ]:
#Convertir las columnas a nomenclatura snake_case
df_monto_procesado.columns=df_monto_procesado.columns.str.replace("Monto enviado por ","enviado_por_")
df_monto_procesado.columns=df_monto_procesado.columns.str.replace("Monto recibido por ","recibido_por_")
df_monto_procesado.columns=df_monto_procesado.columns.str.replace(", S.A.","")
df_monto_procesado.columns=df_monto_procesado.columns.str.replace(" S.A.","")
df_monto_procesado.columns=df_monto_procesado.columns.str.replace(" de C.V.","")
df_monto_procesado.columns=df_monto_procesado.columns.str.replace(" ","_")
df_monto_procesado.columns=df_monto_procesado.columns.str.lower()

<ipython-input-117-1a43c9a9c7be>:4: FutureWarning: The default value of regex will change from True to False in a future version.
  df_monto_procesado.columns=df_monto_procesado.columns.str.replace(", S.A.","")
<ipython-input-117-1a43c9a9c7be>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df_monto_procesado.columns=df_monto_procesado.columns.str.replace(" S.A.","")
<ipython-input-117-1a43c9a9c7be>:6: FutureWarning: The default value of regex will change from True to False in a future version.
  df_monto_procesado.columns=df_monto_procesado.columns.str.replace(" de C.V.","")

In [ ]:
#Conversión de datos a tipo númerico , a execpción de la primera columna
#Los datos que no se puedan convertir se volveran valores NaN
df_monto_procesado.iloc[:,1:] = df_monto_procesado.iloc[:,1:].applymap(lambda x: pd.to_numeric(x, errors='coerce'))

#Convertimos la columna fecha a datetime
df_monto_procesado['fecha'] = pd.to_datetime(df_monto_procesado['fecha'], format='%d/%m/%Y')

#Revisamos que el cambio de variable se halla realizado correctamente

df_monto_procesado.dtypes

fecha                                                 datetime64[ns]
total_de_monto_enviado                                         int64
enviado_por_accendo_banco                                      int64
enviado_por_banco_actinver                                     int64
enviado_por_banca_afirme                                       int64
                                                           ...
recibido_por_banco_sabadell                                    int64
recibido_por_banco_santander_(méxico)                          int64
recibido_por_scotiabank_inverlat                               int64
recibido_por_sistema_de_transferencias_y_pagos_stp             int64
recibido_por_banco_ve_por_mas                                  int64
Length: 77, dtype: object

In [ ]:
columnas_nulas_df_monto_procesado = df_monto_procesado.columns[df_monto_procesado.isnull().any()].tolist()

print(f"Las columnas que tienen valores nulos son: {columnas_nulas_df_monto_procesado}")

#No hay columnas con valores nulos

Las columnas que tienen valores nulos son: []

In [ ]:
df_monto_procesado = df_monto_procesado.reset_index(drop=True)
df_monto_procesado.shape

#En la limpieza de datos , no se encontraron valores NaN, por lo que el tamaño del dataframe no se modificó

(1205, 77)

## Dataframe transacciones

**operaciones_realizadas.csv** 

*Descripción:* Cantidad de transacciones diarias, enviadas y recibidas por cada institución bancaria. 

Este dataset consta de 1205 renglones y 77 columnas. La segunda columna corresponde al número total de operaciones enviadas, las siguientes 35 columnas corresponden al número de operaciones enviadas por diferentes entidades bancarias. La columna 38 corresponde al número total de operaciones recibidas y las siguientes 39 columnas corresponden al número de operaciones recibidas por diferentes entidades bancarias.

#### EXploración inicial

In [ ]:
df_transacciones

,Fecha,Total de operaciones enviadas,"Operaciones enviadas por Accendo Banco, S.A.","Operaciones enviadas por Banco Actinver, S.A.","Operaciones enviadas por Banca Afirme, S.A.","Operaciones enviadas por Opciones Empresariales del Noreste, S.A. de C.V.","Operaciones enviadas por Banco Autofin México, S.A.","Operaciones enviadas por Banco Azteca, S.A.","Operaciones enviadas por Banco del Bajío, S.A.","Operaciones enviadas por Banco Nacional de México, S.A.",...,"Operaciones recibidas por Intercam Banco, S.A.","Operaciones recibidas por Banco Invex, S.A.","Operaciones recibidas por Banca Mifel, S.A.","Operaciones recibidas por Banco Multiva, S.A.","Operaciones recibidas por Banco Pagatodo, S.A.","Operaciones recibidas por Banco Sabadell, S.A.","Operaciones recibidas por Banco Santander (México), S.A.","Operaciones recibidas por Scotiabank Inverlat, S.A.","Operaciones recibidas por Sistema de Transferencias y Pagos STP, S.A. de C.V.","Operaciones recibidas por Banco Ve Por Mas, S.A."
0,30/09/2019,1747,0,28,17,23,0,76,58,718,...,21,13,21,0,49,0,55,3,15,14
1,01/10/2019,1675,0,6,2,1,0,44,57,899,...,11,1,2,0,17,0,41,1,22,3
2,02/10/2019,1943,0,1,4,1,0,58,69,1021,...,19,1,13,0,22,0,38,1,13,9
3,03/10/2019,1759,0,9,7,18,0,62,76,844,...,4,0,5,0,18,0,56,22,16,11
4,04/10/2019,1554,0,4,11,9,0,52,48,631,...,2,0,4,0,14,0,49,143,7,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1200,12/01/2023,11463,0,0,28,0,1,2152,180,704,...,16,0,1,0,6,0,1261,182,190,0
1201,13/01/2023,16490,0,0,32,0,1,2495,548,1608,...,8,0,3,0,4,1,1561,304,223,0
1202,14/01/2023,8383,0,2,9,0,0,493,258,820,...,1,1,0,0,1,0,1428,143,102,1
1203,15/01/2023,6638,0,1,5,0,0,986,191,585,...,2,0,0,0,2,0,1672,106,157,0
1204,16/01/2023,10455,0,0,19,0,0,1820,215,898,...,6,0,5,0,2,0,953,163,243,1

In [ ]:
df_transacciones.columns
df_transacciones.dtypes
df_transacciones.shape
df_transacciones.head()
df_transacciones.tail()

,Fecha,Total de operaciones enviadas,"Operaciones enviadas por Accendo Banco, S.A.","Operaciones enviadas por Banco Actinver, S.A.","Operaciones enviadas por Banca Afirme, S.A.","Operaciones enviadas por Opciones Empresariales del Noreste, S.A. de C.V.","Operaciones enviadas por Banco Autofin México, S.A.","Operaciones enviadas por Banco Azteca, S.A.","Operaciones enviadas por Banco del Bajío, S.A.","Operaciones enviadas por Banco Nacional de México, S.A.",...,"Operaciones recibidas por Intercam Banco, S.A.","Operaciones recibidas por Banco Invex, S.A.","Operaciones recibidas por Banca Mifel, S.A.","Operaciones recibidas por Banco Multiva, S.A.","Operaciones recibidas por Banco Pagatodo, S.A.","Operaciones recibidas por Banco Sabadell, S.A.","Operaciones recibidas por Banco Santander (México), S.A.","Operaciones recibidas por Scotiabank Inverlat, S.A.","Operaciones recibidas por Sistema de Transferencias y Pagos STP, S.A. de C.V.","Operaciones recibidas por Banco Ve Por Mas, S.A."
1200,12/01/2023,11463,0,0,28,0,1,2152,180,704,...,16,0,1,0,6,0,1261,182,190,0
1201,13/01/2023,16490,0,0,32,0,1,2495,548,1608,...,8,0,3,0,4,1,1561,304,223,0
1202,14/01/2023,8383,0,2,9,0,0,493,258,820,...,1,1,0,0,1,0,1428,143,102,1
1203,15/01/2023,6638,0,1,5,0,0,986,191,585,...,2,0,0,0,2,0,1672,106,157,0
1204,16/01/2023,10455,0,0,19,0,0,1820,215,898,...,6,0,5,0,2,0,953,163,243,1

#### Limpieza inicial

In [ ]:

#Convertir las columnas a nomenclatura snake_case

df_transacciones.columns = df_transacciones.columns.str.replace("Operaciones enviadas por","enviadas")
df_transacciones.columns = df_transacciones.columns.str.replace("Operaciones recibidas por","recibidas")
df_transacciones.columns = df_transacciones.columns.str.replace(", S.A.","")
df_transacciones.columns = df_transacciones.columns.str.replace(" S.A.","")
df_transacciones.columns = df_transacciones.columns.str.replace(" de C.V.","")
df_transacciones.columns = df_transacciones.columns.str.replace(", S.N.C.","")
df_transacciones.columns = df_transacciones.columns.str.replace(" ","_")
df_transacciones.columns = df_transacciones.columns.str.lower()

<ipython-input-177-95a7c8504150>:6: FutureWarning: The default value of regex will change from True to False in a future version.
  df_transacciones.columns = df_transacciones.columns.str.replace(", S.A.","")
<ipython-input-177-95a7c8504150>:7: FutureWarning: The default value of regex will change from True to False in a future version.
  df_transacciones.columns = df_transacciones.columns.str.replace(" S.A.","")
<ipython-input-177-95a7c8504150>:8: FutureWarning: The default value of regex will change from True to False in a future version.
  df_transacciones.columns = df_transacciones.columns.str.replace(" de C.V.","")
<ipython-input-177-95a7c8504150>:9: FutureWarning: The default value of regex will change from True to False in a future version.
  df_transacciones.columns = df_transacciones.columns.str.replace(", S.N.C.","")

In [ ]:
#Convertir todos los valores de la columna en datos del tipo numerico
#Los datos que no se puedan convertir a tipo numerico se volverán NaN

for i in range(1,len(df_transacciones.columns)):
    a=df_transacciones.columns[i]
    df_transacciones[a] = pd.to_numeric(df_transacciones[a], errors='coerce')

#Convertimos la columna fecha a datetime
df_transacciones['fecha'] = pd.to_datetime(df_transacciones['fecha'], format='%d/%m/%Y')

#Revisamos que se halla realizado correctamente el cambio de variable

df_transacciones.dtypes

fecha                                              datetime64[ns]
total_de_operaciones_enviadas                               int64
enviadas_accendo_banco                                      int64
enviadas_banco_actinver                                     int64
enviadas_banca_afirme                                       int64
                                                        ...
recibidas_banco_sabadell                                    int64
recibidas_banco_santander_(méxico)                          int64
recibidas_scotiabank_inverlat                               int64
recibidas_sistema_de_transferencias_y_pagos_stp             int64
recibidas_banco_ve_por_mas                                  int64
Length: 77, dtype: object

In [ ]:
columnas_nulas_df_transacciones = df_transacciones.columns[df_transacciones.isnull().any()].tolist()
print(f"Las columnas que tienen valores nulos son: {columnas_nulas_df_transacciones}")

#No hay valores nulos

Las columnas que tienen valores nulos son: []

In [ ]:

df_transacciones = df_transacciones.reset_index(drop=True)
df_transacciones.shape

#En la limpieza de datos , no se encontraron valores NaN, por lo que el tamaño del dataframe no se modificó

(1205, 77)

### Exportación de archivos limpios a CSV

Ya que terminamos con la limpieza de todos los dataframes, crearemos nuevamente un conjuntos de archivos pero con los dataframes sin valores nulos y con los tipos de datos correctos para esté proyecto

In [ ]:
#Exportamos los dataframes limpios a un archivo csv

df_una_transaccion.to_csv(f'{ruta}/cuentas_una_transaccion_limpio.csv')
df_cuentas_validas.to_csv(f'{ruta}/cuentas_validad_limpio.csv')
df_transacciones.to_csv(f'{ruta}/transacciones_limpio.csv')
df_smartphones.to_csv(f'{ruta}/smarphones_limpio.csv')
df_monto_procesado.to_csv(f'{ruta}/monto_procesado_limpio.csv')

### Creación de dataframes con datos estadísticos

Para aquellos data frames que no contienen valores acumulativos, se crearon nuevos data frames con información estádistica de medidas de tendencia central, valores máximo y minímo y cuartiles para darnos una idea de la tendencia de los datos.

In [ ]:
estadisticos_df_transacciones = round(df_transacciones.describe(),0)
estadisticos_df_transacciones

,total_de_operaciones_enviadas,enviadas_accendo_banco,enviadas_banco_actinver,enviadas_banca_afirme,enviadas_opciones_empresariales_del_noreste,enviadas_banco_autofin_méxico,enviadas_banco_azteca,enviadas_banco_del_bajío,enviadas_banco_nacional_de_méxico,enviadas_banco_ahorro_famsa,...,recibidas_intercam_banco,recibidas_banco_invex,recibidas_banca_mifel,recibidas_banco_multiva,recibidas_banco_pagatodo,recibidas_banco_sabadell,recibidas_banco_santander_(méxico),recibidas_scotiabank_inverlat,recibidas_sistema_de_transferencias_y_pagos_stp,recibidas_banco_ve_por_mas
count,1205.0,1205.0,1205.0,1205.0,1205.0,1205.0,1205.0,1205.0,1205.0,1205.0,...,1205.0,1205.0,1205.0,1205.0,1205.0,1205.0,1205.0,1205.0,1205.0,1205.0
mean,5627.0,0.0,0.0,10.0,8.0,1.0,719.0,85.0,736.0,1.0,...,6.0,0.0,2.0,0.0,9.0,1.0,393.0,72.0,42.0,1.0
std,3626.0,0.0,2.0,12.0,9.0,2.0,629.0,88.0,250.0,3.0,...,9.0,1.0,3.0,0.0,5.0,2.0,502.0,32.0,36.0,4.0
min,432.0,0.0,0.0,0.0,0.0,0.0,11.0,0.0,134.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,8.0,1.0,0.0,0.0
25%,2573.0,0.0,0.0,5.0,1.0,0.0,144.0,26.0,555.0,0.0,...,1.0,0.0,1.0,0.0,5.0,0.0,79.0,51.0,13.0,0.0
50%,5129.0,0.0,0.0,8.0,5.0,0.0,623.0,58.0,729.0,0.0,...,3.0,0.0,2.0,0.0,8.0,0.0,107.0,68.0,33.0,1.0
75%,8002.0,0.0,0.0,13.0,13.0,1.0,1118.0,123.0,887.0,0.0,...,9.0,0.0,3.0,0.0,11.0,0.0,735.0,88.0,63.0,2.0
max,22718.0,5.0,28.0,331.0,144.0,39.0,2495.0,674.0,1665.0,57.0,...,115.0,13.0,36.0,10.0,54.0,32.0,2377.0,304.0,243.0,52.0

In [ ]:
estadisticos_df_monto_procesado = round(df_monto_procesado.describe(),2)
estadisticos_df_monto_procesado

,total_de_monto_enviado,enviado_por_accendo_banco,enviado_por_banco_actinver,enviado_por_banca_afirme,enviado_por_opciones_empresariales_del_noreste,enviado_por_banco_autofin_méxico,enviado_por_banco_azteca,enviado_por_banco_del_bajío,enviado_por_banco_nacional_de_méxico,enviado_por_banco_ahorro_famsa,...,recibido_por_intercam_banco,recibido_por_banco_invex,recibido_por_banca_mifel,recibido_por_banco_multiva,recibido_por_banco_pagatodo,recibido_por_banco_sabadell,recibido_por_banco_santander_(méxico),recibido_por_scotiabank_inverlat,recibido_por_sistema_de_transferencias_y_pagos_stp,recibido_por_banco_ve_por_mas
count,1205.00,1205.00,1205.00,1205.00,1205.00,1205.00,1205.00,1205.00,1205.00,1205.00,...,1205.00,1205.00,1205.00,1205.00,1205.00,1205.00,1205.00,1205.00,1205.00,1205.00
mean,4684200.48,0.03,226.82,12899.73,1586.59,473.88,447122.09,137204.17,639867.86,365.54,...,1873.94,52.51,1877.64,55.89,1252.59,135.36,159442.79,82194.00,300879.48,1249.20
std,3043616.96,0.88,1190.90,18912.04,5069.37,1501.40,371718.21,188109.26,264253.95,5203.35,...,3645.28,445.14,3576.80,561.08,2628.34,1026.65,127000.74,58077.22,1000560.16,8981.66
min,163872.00,0.00,0.00,0.00,0.00,0.00,1766.00,0.00,78452.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,874.00,5.00,0.00,0.00
25%,2432153.00,0.00,0.00,2450.00,0.00,0.00,99251.00,21791.00,452567.00,0.00,...,10.00,0.00,0.00,0.00,61.00,0.00,72617.00,49494.00,4491.00,0.00
50%,4272056.00,0.00,0.00,7231.00,188.00,0.00,420845.00,76045.00,605381.00,0.00,...,411.00,0.00,500.00,0.00,379.00,0.00,120525.00,71645.00,21528.00,3.00
75%,6244596.00,0.00,0.00,15948.00,1047.00,85.00,670801.00,178445.00,779057.00,0.00,...,2095.00,0.00,2099.00,0.00,1285.00,0.00,209521.00,102737.00,113800.00,800.00
max,24236665.00,30.00,16000.00,262357.00,101291.00,16000.00,1675890.00,2118250.00,2043697.00,166666.00,...,35515.00,10100.00,44689.00,9000.00,40075.00,24001.00,1006960.00,754815.00,10681158.00,300070.00

In [ ]:
estadisticos_df_cuentas_validas = df_cuentas_validas.describe()
round(estadisticos_df_cuentas_validas, 0)

,total_de_cuentas_validadas,abc_capital,banco_actinver,banca_afirme,opciones_empresariales_del_noreste,banco_autofin_méxico,banco_azteca,banco_del_bajío,banco_nacional_de_méxico,bancoppel,...,banco_invex,banca_mifel,banco_multiva,banco_pagatodo,banco_sabadell,banco_santander_(méxico),scotiabank_inverlat,sistema_de_transferencias_y_pagos_stp,operadora_de_pagos_móviles_de_méxicode,banco_ve_por_mas
count,968.0,968.0,968.0,968.0,968.0,968.0,968.0,968.0,968.0,968.0,...,968.0,968.0,968.0,968.0,968.0,968.0,968.0,968.0,968.0,968.0
mean,13736.0,0.0,0.0,39.0,3.0,1.0,376.0,12.0,1675.0,2360.0,...,0.0,2.0,0.0,9.0,0.0,235.0,169.0,6.0,0.0,0.0
std,50713.0,1.0,1.0,92.0,4.0,1.0,175.0,12.0,49473.0,2078.0,...,1.0,2.0,1.0,12.0,3.0,4439.0,101.0,34.0,0.0,1.0
min,-1074098.0,-19.0,-26.0,-2620.0,-38.0,-2.0,-3425.0,-196.0,-1085669.0,-549.0,...,-4.0,-22.0,-17.0,-16.0,-73.0,-98011.0,-282.0,-931.0,0.0,-2.0
25%,10536.0,0.0,0.0,22.0,0.0,0.0,314.0,8.0,1072.0,922.0,...,0.0,1.0,0.0,3.0,0.0,201.0,102.0,3.0,0.0,0.0
50%,12630.0,0.0,0.0,33.0,2.0,0.0,388.0,12.0,1404.0,2155.0,...,0.0,1.0,0.0,5.0,0.0,240.0,166.0,7.0,0.0,0.0
75%,16292.0,0.0,0.0,49.0,5.0,1.0,442.0,17.0,1838.0,3322.0,...,0.0,3.0,0.0,10.0,1.0,284.0,230.0,12.0,0.0,1.0
max,1101437.0,4.0,3.0,313.0,23.0,6.0,1438.0,140.0,1088807.0,26813.0,...,15.0,10.0,2.0,124.0,73.0,97062.0,567.0,174.0,2.0,4.0

## Resolución de las preguntas planteadas

En esta sección utilizaremos la información de los dataframes para responder las preguntas que nos planteamos en el postwork 2

### ¿Cuáles son las entidades financieras con mayor y menor número de cuentas validadas?

Los bancos con menor numero de cuentas validadas son: 
*  Fundación donde banco : 4
*  Operadora de pagos moviles de mexico : 19 
*  Banco base : 24 
*  Banco multiva : 24 
*  Bansi : 28 

Los bancos con mayor numero de cuentas validadas son: 
* BBVA Bancomer:                7964562
* Bancoppel:                   2284164
* Banco Nacional de México:    1620960
* Banco Azteca:                 363863
* HSBC México:                  269662

In [ ]:
menor_cuentas_validadas = df_cuentas_validas.sum().sort_values(ascending=True).head(5)
print(f"Las entidades financieras con menor cantidad de cuentas validadas son : \n {menor_cuentas_validadas}")

Las entidades financieras con menor cantidad de cuentas validadas son :
 fundación_dondé_banco                      4
operadora_de_pagos_móviles_de_méxicode    19
banco_base                                24
banco_multiva                             28
bansi                                     28
dtype: int64

<ipython-input-131-1432a32c663e>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  menor_cuentas_validadas = df_cuentas_validas.sum().sort_values(ascending=True).head(5)

In [ ]:
#Se coloca Iloc para quitar la columna de cuentas validadas totales 
mayor_cuentas_validadas = df_cuentas_validas.iloc[:, 2:].sum().sort_values(ascending= False).head(5)

print(f"Las entidades financieras con mayor cantidad de cuentas validadas son : \n {mayor_cuentas_validadas}")

Las entidades financieras con mayor cantidad de cuentas validadas son :
 bbva_bancomer               7964562
bancoppel                   2284164
banco_nacional_de_méxico    1620960
banco_azteca                 363863
hsbc_méxico                  269662
dtype: int64

###¿Cuál es la proporción de cuentas registradas que han realizado al menos un cobro o un pago mediante CoDi?

El dataframe df_una_transaccion contiene datos acumulativos, entonces para sacar la proporcion de cuentas validadas que han realizado por lo menos un pago o un cobro se tomara el ultimo dato del dataframe. 

Para sacar la proporción se dividirá el numero de cuentas registradas que han realizado por lo menos un cobro o un pago entre el total de cuentas validadas.

EL porcentaje calculado fue: 
* Cuentas registradas con al menos un pago: 9.3 %
* Cuentas registradas con al menos un cobro: 6.2 %

In [ ]:

#El dataframe una transaccion es acumulativo , entonces para sacar la proporcion de cuentas validadas 
#que han realizado por lo menos un pago o un cobro se tomara el ultimo dato

df_una_transaccion.iloc[-1,1]  #Cuentas que han realizado por lo menos un pago
df_una_transaccion.iloc[-1,2]  #Cuentas que han realizado por lo menos un cobro
df_cuentas_validas.sum().head(1) # Total de cuentas validadas

proporción_cuentas_un_pago = df_una_transaccion.iloc[-1,1]/df_cuentas_validas.sum().head(1) 
proporción_cuentas_un_cobro = df_una_transaccion.iloc[-1,2]/df_cuentas_validas.sum().head(1)  

print(f"El porcentaje de cuentas que han realizado por lo menos un pago es : {round(proporción_cuentas_un_pago*100,2)}")
print(f"El porcentaje de cuentas que han realizado por lo menos un cobro es : {round(proporción_cuentas_un_cobro*100,2)}")

El porcentaje de cuentas que han realizado por lo menos un pago es : total_de_cuentas_validadas    9.29
dtype: float64
El porcentaje de cuentas que han realizado por lo menos un cobro es : total_de_cuentas_validadas    6.16
dtype: float64

<ipython-input-176-2f875df759d5>:7: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df_cuentas_validas.sum().head(1) # Total de cuentas validadas
<ipython-input-176-2f875df759d5>:9: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  proporción_cuentas_un_pago = df_una_transaccion.iloc[-1,1]/df_cuentas_validas.sum().head(1)
<ipython-input-176-2f875df759d5>:10: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  proporción_cuentas_un_cobro = df_una_transaccion.iloc[-1,2]/df_cuentas_validas.sum().head(1)

### ¿Cúal ha sido el promedio por año de las cuentas que han realizado al menos un cobro o un pago mediante CoDi?

El dataframe una transaccion es acumulativo , para sacar los datos por fecha sacariamos los datos que corresponden al ultimo día del año , dividido entre el numero de días (365)

Para el caso del año 2019 , tenemos datos a partir del 23 de Octubre , el número de días al 31 de diciembre son 69 , por lo que en lugar de dividir entre 365 días , se dividirá entre 69 días

* 31/12/2019
* 31/12/2020
* 31/12/2021
* 31/12/2022

Promedio de cuentas en 2019 han realizado por lo menos un cobro o un pago: 

* Por lo menos un pago: 1030.84 transacciones diarias
* Por lo menos un cobro: 878.3 transacciones diarias

Promedio de cuentas en 2020 han realizado por lo menos un cobro o un pago: 

* Por lo menos un pago: 721.48 transacciones diarias
* Por lo menos un cobro: 585.26 transacciones diarias

Promedio de cuentas en 2021 han realizado por lo menos un cobro o un pago: 

* Por lo menos un pago: 1190.53  transacciones diarias
* Por lo menos un cobro: 935.76 transacciones diarias

Promedio de cuentas en 2022 han realizado por lo menos un cobro o un pago: 

* Por lo menos un pago: 1210.38 transacciones diarias
* Por lo menos un cobro: 533.11 transacciones diarias

In [ ]:
df_filtrado_1 = df_una_transaccion[(df_una_transaccion['fecha'].dt.month == 12) & (df_una_transaccion['fecha'].dt.day == 31)]

df_filtrado_1 = df_filtrado_1.sort_values('fecha', ascending = False)

#Número  de cuentas que por lo menos realiza un coboro o un pag por año

# transacciones 2022
transacciones_un_pago_2022 = df_filtrado_1.iloc[0,1] - df_filtrado_1.iloc[1,1]
transacciones_un_cobro_2022 = df_filtrado_1.iloc[0,2] - df_filtrado_1.iloc[1,2]

# transacciones 2021
transacciones_un_pago_2021 = df_filtrado_1.iloc[1,1] - df_filtrado_1.iloc[2,1]
transacciones_un_cobro_2021 = df_filtrado_1.iloc[1,2] - df_filtrado_1.iloc[2,2]

# transacciones 2020
transacciones_un_pago_2020 = df_filtrado_1.iloc[2,1] - df_filtrado_1.iloc[3,1]
transacciones_un_cobro_2020 = df_filtrado_1.iloc[2,2] - df_filtrado_1.iloc[3,2]

# transacciones 2019
transacciones_un_pago_2019 = df_filtrado_1.iloc[3,1]
transacciones_un_cobro_2019 = df_filtrado_1.iloc[3,2]



# Promedio transacciones 2022

# Un solo pago: 1210.37 transacciones diarias
promedio_diario_un_pago_2022 = round(transacciones_un_pago_2022 / 365,2)
# Un solo cobro: 533.11 transacciones diarias
promedio_diario_un_cobro_2022 = round(transacciones_un_cobro_2022 / 365,2)


# Promedio transacciones 2021
# Un solo pago: 1190.53 transacciones diarias
promedio_diario_un_pago_2021 = round(transacciones_un_pago_2021 / 365,2)
# Un solo cobro: 935.76 transacciones diarias
promedio_diario_un_cobro_2021 =round(transacciones_un_cobro_2021 / 365,2)

# Promedio transacciones 2020
# Un solo pago: 723.45 transacciones diarias
promedio_diario_un_pago_2020 = round(transacciones_un_pago_2020 / 366,2)
# Un solo cobro: 586.86 transacciones diarias
promedio_diario_un_cobro_2020 = round(transacciones_un_cobro_2020 / 366,2)

# Promedio transacciones 2019
# Un solo pago: 1030.84 transacciones diarias
promedio_diario_un_pago_2019 = round(transacciones_un_pago_2019 / 69,2)
# Un solo cobro: 878.30 transacciones diarias
promedio_diario_un_cobro_2019 = round(transacciones_un_cobro_2019 / 69,2)

#Crea una tabla para mostrar los resultados

promedio_cuentas = [
    {"Año": 2019, "Promedio de cuentas que han realizado un pago":promedio_diario_un_pago_2019, "Promedio de cuentas que han realizado un cobro": promedio_diario_un_cobro_2019},
    {"Año": 2020, "Promedio de cuentas que han realizado un pago":promedio_diario_un_pago_2020, "Promedio de cuentas que han realizado un cobro": promedio_diario_un_cobro_2020},
    {"Año": 2021, "Promedio de cuentas que han realizado un pago":promedio_diario_un_pago_2021, "Promedio de cuentas que han realizado un cobro": promedio_diario_un_cobro_2021},
    {"Año": 2022, "Promedio de cuentas que han realizado un pago":promedio_diario_un_pago_2022, "Promedio de cuentas que han realizado un cobro": promedio_diario_un_cobro_2022}
]

df_promedio_cuentas_un_pago_un_cobro = pd.DataFrame(promedio_cuentas)


# Imprime el encabezado de la tabla
print("Año".ljust(10), "promedio_cuentas_pago".ljust(20), "Promedio_cuentas_cobro".ljust(20))
print("-" * 10, "-" *22, "-" *22)

# Imprime los datos de la tabla
for i, fila in df_promedio_cuentas_un_pago_un_cobro.iterrows():
    print(str(fila["Año"]).ljust(10), str(fila["Promedio de cuentas que han realizado un pago"]).ljust(22), str(fila["Promedio de cuentas que han realizado un cobro"]).ljust(22))

Año        promedio_cuentas_pago Promedio_cuentas_cobro
---------- ---------------------- ----------------------
2019.0     1030.84                878.3
2020.0     721.48                 585.26
2021.0     1190.53                935.76
2022.0     1210.38                533.11

###¿Cúal es el número promedio de transacciones realizadas por año?

El dataframe de transacciones no es acumulativo , por lo que se sumarán el total de operaciones enviadas por año .

En el dataframe viene el numero total de operaciones enviadas y el número total de operaciones recibidas. Hicimos la comparación y notamos que por cada transacción enviada , hay una transacción recibida. Por lo que para efectos de cálculo solo utilizaremos la columna de total_de_operaciones_enviadas.


* Promedio de transacciones 2019 : 1569.18 
* Promedio de transacciones 2020 : 2764.47 
* Promedio de transacciones 2021 : 6721.55
* Promedio de transacciones 2022 : 8241.04
* Promedio de transacciones 2023 : 10094.0

In [ ]:

# AÑO 2019: 1569.18 transacciones
transacciones_2019 = df_transacciones[df_transacciones['fecha'].dt.year == 2019]['total_de_operaciones_enviadas'].sum()

transacciones_2019_2 = df_transacciones[df_transacciones['fecha'].dt.year == 2019]['total_de_operaciones_recibidas'].sum()

transacciones_2019 == transacciones_2019_2

# Al analizar el df df_transacciones se notó que existen dos columnas con la misma información: total_de_operaciones_enviadas y 
# total_de_operaciones_recibidas, esto es porque una transacción involucra una operación de enviar y otra de recibir. 

promedio_transacciones_2019 = round(transacciones_2019 / len(df_transacciones[df_transacciones['fecha'].dt.year == 2019]['total_de_operaciones_recibidas']),2)



# AÑO 2020: 2764.46 transacciones
transacciones_2020 = df_transacciones[df_transacciones['fecha'].dt.year == 2020]['total_de_operaciones_enviadas'].sum()
promedio_transacciones_2020 = round(transacciones_2020 / len(df_transacciones[df_transacciones['fecha'].dt.year == 2020]['total_de_operaciones_recibidas']),2)



# AÑO 2021: 6721.54 transacciones
transacciones_2021 = df_transacciones[df_transacciones['fecha'].dt.year == 2021]['total_de_operaciones_enviadas'].sum()
promedio_transacciones_2021 = round(transacciones_2021 / len(df_transacciones[df_transacciones['fecha'].dt.year == 2021]['total_de_operaciones_recibidas']),2)



# AÑO 2022: 8241.03 transacciones
transacciones_2022 = df_transacciones[df_transacciones['fecha'].dt.year == 2022]['total_de_operaciones_enviadas'].sum()
promedio_transacciones_2022 = round(transacciones_2022 / len(df_transacciones[df_transacciones['fecha'].dt.year == 2022]['total_de_operaciones_recibidas']),2)


# AÑO 2023: 10094 transacciones
transacciones_2023 = df_transacciones[df_transacciones['fecha'].dt.year == 2023]['total_de_operaciones_enviadas'].sum()
promedio_transacciones_2023 = round( transacciones_2023 / len(df_transacciones[df_transacciones['fecha'].dt.year == 2023]['total_de_operaciones_recibidas']),2)



#Crea una tabla para mostrar los resultados

promedio_transaciones = [
    {"Año": 2019, "Promedio de transacciones":promedio_transacciones_2019},
    {"Año": 2020, "Promedio de transacciones":promedio_transacciones_2020},
    {"Año": 2021, "Promedio de transacciones":promedio_transacciones_2021},
    {"Año": 2022, "Promedio de transacciones":promedio_transacciones_2022},
    {"Año": 2022, "Promedio de transacciones":promedio_transacciones_2023}
]


df_promedio_transacciones = pd.DataFrame(promedio_transaciones)


# Imprime el encabezado de la tabla
print("Año".ljust(10), "promedio_transacciones".ljust(20))
print("-" * 10, "-" *22)

# Imprime los datos de la tabla
for i, fila in df_promedio_transacciones.iterrows():
    print(str(fila["Año"]).ljust(10), str(fila["Promedio de transacciones"]).ljust(22))

Año        promedio_transacciones
---------- ----------------------
2019.0     1569.18
2020.0     2764.47
2021.0     6721.55
2022.0     8241.04
2022.0     10094.0

### ¿ Cúales son las entidades financieras con el mayor número de cuentas enviadas y recibidas?

El dataframe df_transacciones tiene la información del número de transacciones que envia y recibe cada banco. Para separar el número de cuentas enviadas y recibidas, lo separamos en dos con el comando iloc[].

Entidades financieras con el mayor número de operaciones enviadas:

* enviadas_bbva_bancomer :              2507436
* enviadas_banco_nacional_de_méxico :    886641
* enviadas_banco_azteca:                 866257
* enviadas_bancoppel:                    586699
* enviadas_hsbc_méxico  :                492246

Entidades financieras con el mayor número de operaciones recibidas:

* recibidas_bbva_bancomer   :            2331377
* recibidas_banco_inbursa  :             1132358
* recibidas_banco_nacional_de_méxico :     859342
* recibidas_hsbc_méxico  :                512358
* recibidas_banco_santander_(méxico) :    473411

In [ ]:

 
#Para saber a partir de que número de columna son transacciones recibidas, con el nombre de la columna , conseguimos el número de columna

column_number = df_transacciones.columns.get_loc('total_de_operaciones_recibidas')

#Empezamos a partir de la columna 2 , para que en el resultado no salíera el total de transacciones enviadas

transacciones_enviadas_bancos = df_transacciones.iloc[:,2:column_number].sum().sort_values(ascending=False).head(5)


# Cantidad de transacciones recibidas por entidad financiera

transacciones_recibidas_bancos = df_transacciones.iloc[:,column_number+1:].sum().sort_values(ascending=False).head(5)


# Impresión de resultados:

#Imprime Operaciones enviadas
print("Entidad_finaciera".ljust(30),"Operaciones_enviadas".ljust(20))
print("-"*30,"-"*20)
print(transacciones_enviadas_bancos)
print("\n"*2)
print("Entidad_finaciera".ljust(35),"Operaciones_recibidas".ljust(20))
print("-"*35,"-"*20)
print(transacciones_recibidas_bancos)

Entidad_finaciera              Operaciones_enviadas
------------------------------ --------------------
enviadas_bbva_bancomer               2507436
enviadas_banco_nacional_de_méxico     886641
enviadas_banco_azteca                 866257
enviadas_bancoppel                    586699
enviadas_hsbc_méxico                  492246
dtype: int64



Entidad_finaciera                   Operaciones_recibidas
----------------------------------- --------------------
recibidas_bbva_bancomer               2331377
recibidas_banco_inbursa               1132358
recibidas_banco_nacional_de_méxico     859342
recibidas_hsbc_méxico                  512358
recibidas_banco_santander_(méxico)     473411
dtype: int64

### ¿Cúal ha sido el monto promedio por año realizado mediante CoDi?

Para resolver está pregunta utilizamos la información del dataframe df_monto_procesado. Este no es dataframe acumulativo , por lo que primero filtramos el monto procesado por año , después aplicamos la agregación sum() y por último lo dividimos entre el número de datos.

Promedio diario del monto de transacciones: 

* 2019 : 82,127.96
* 2020 : 887,115.87
* 2021 : 1,469,326.71
* 2022 :  2,124,231.67
* 2023 : 121,398.28

In [ ]:
# ¿Cuál ha sido el monto promedio por año realizado mediante CoDi?
# El data frame df_monto_procesado muestra datos que no son acumulados en el tiempo. 
# También se analiza que las columnas total_de_monto_enviado y total_de_monto_recibido contienen la siguiente información, ya que 
# en una transacción en monto que se recibe y el que se envía debe ser el mismo. 
monto_procesado_2019 = df_monto_procesado[df_monto_procesado['fecha'].dt.year == 2019]['total_de_monto_enviado'].sum()
monto_procesado_2019_2 = df_monto_procesado[df_monto_procesado['fecha'].dt.year == 2019]['total_de_monto_recibido'].sum()
monto_procesado_2019 == monto_procesado_2019_2

# AÑO 2019
# Monto procesado por día: $ 82,127.95 MXN
promedio_monto_procesado_2019 = round(monto_procesado_2019 / len(df_monto_procesado['fecha'].dt.year == 2019),2)


# AÑO 2020
# Monto procesado por día: $ 887,115.87 MXN
monto_procesado_2020 = df_monto_procesado[df_monto_procesado['fecha'].dt.year == 2020]['total_de_monto_enviado'].sum()
promedio_monto_procesado_2020 = round(monto_procesado_2020 / len(df_monto_procesado['fecha'].dt.year == 2020),2)

# AÑO 2021
# Monto procesado por día: $ 1,469,326.70 MXN
monto_procesado_2021 = df_monto_procesado[df_monto_procesado['fecha'].dt.year == 2021]['total_de_monto_enviado'].sum()
promedio_monto_procesado_2021 = round(monto_procesado_2021 / len(df_monto_procesado['fecha'].dt.year == 2021),2)


# AÑO 2022
# Monto procesado por día: $ 2,124,231.67 MXN
monto_procesado_2022 = df_monto_procesado[df_monto_procesado['fecha'].dt.year == 2022]['total_de_monto_enviado'].sum()
promedio_monto_procesado_2022 = round( monto_procesado_2022 / len(df_monto_procesado['fecha'].dt.year == 2022),2)


# AÑO 2023
# Monto procesado por día: $ 121,398.27 MXN
monto_procesado_2023 = df_monto_procesado[df_monto_procesado['fecha'].dt.year == 2023]['total_de_monto_enviado'].sum()
promedio_monto_procesado_2023 = round( monto_procesado_2023 / len(df_monto_procesado['fecha'].dt.year == 2023),2)



#Impresión de resultados

print("año".ljust(5),"monto_promedio".ljust(15))
print("-"*5,"-"*15)
print(f"2019  {promedio_monto_procesado_2019}")
print(f"2020  {promedio_monto_procesado_2020}")
print(f"2021  {promedio_monto_procesado_2021}")
print(f"2022  {promedio_monto_procesado_2022}")
print(f"2023  {promedio_monto_procesado_2023}")

año   monto_promedio
----- ---------------
2019  82127.96
2020  887115.87
2021  1469326.71
2022  2124231.67
2023  121398.28

###¿Cuál es el porcentaje de dispositivos Android y iOS registrados en CoDi?

Para resolver está pregunta sacamos un subconjunto del dataframe df_smarphones, ya que solo nos interesa el total de dispositivos y no el nuúmero de dispositivos por entidad financiera. Despues agregamos una columna para sumar el total de dispositivos enrolados. Con esas columnas tuvimos la información necesaria para sacar el porcentaje por sistema operativo.

El número de dispositivos enrolados de cada sistema operativo , cambia todos los días , pero en promedio tenemos que 74.92 % de los dispositivos que usan CoDi son android y el 25.08 % de los dispositivos unan ios.

In [ ]:
pd.options.mode.chained_assignment = None 
#Vamos a sacar el subconjunto de datos donde solo tengamos las columnas del total dispositivos androi y total dispositivos Ios
df_smarphones_android_ios_enrolados =df_smartphones[["total_de_dispositivos_android_enrolados","total_de_dispositivos_ios_enrolados"]]

#Agregamos una tercera columna que nos sume el total de dispositivos enrolados

df_smarphones_android_ios_enrolados["total_dispositivos"] = df_smarphones_android_ios_enrolados.apply(lambda x: x['total_de_dispositivos_android_enrolados'] + x['total_de_dispositivos_ios_enrolados'], axis=1)


#Sacamos el porcentaje de dispositivos android enrolados

df_smarphones_android_ios_enrolados["porcentaje_android"] = df_smarphones_android_ios_enrolados.apply(lambda x: round((x['total_de_dispositivos_android_enrolados'] / x['total_dispositivos'])*100,2), axis=1)

#Sacamos el porcentaje de dispositivos ios enrolados

df_smarphones_android_ios_enrolados["porcentaje_ios"] = df_smarphones_android_ios_enrolados.apply(lambda x: round((x['total_de_dispositivos_ios_enrolados'] / x['total_dispositivos'])*100,2), axis=1)

porcentaje_android = round(df_smarphones_android_ios_enrolados["porcentaje_android"].mean(),2)
porcentaje_ios =round(df_smarphones_android_ios_enrolados["porcentaje_ios"].mean(),2)

print("sistema_operativo".ljust(20),"porcentaje".ljust(10))
print("-"*20,"-"*10)
print("android".ljust(20),f"{porcentaje_android}")
print("ios".ljust(20),f"{porcentaje_ios}")

sistema_operativo    porcentaje
-------------------- ----------
android              74.92
ios                  25.08

### Cuáles han sido las medidas de tendencia central, los valores máximos y mínimos y los cuartiles de las columnas 'transacciones_diarias_al_menos_un_pago' y 'transacciones_diarias_al_menos_un_cobro' del data frame 'df_una_transaccion'?

Dado que el df_una_transaccion contiene datos acumulados, fue necesario sacar el número de transacciones por día para resolver esta pregunta.

Para resolverlo, se agregarón dos columnas al data frame: 
* transacciones_diarias_al_menos_un_pago
* transacciones_diarias_al_menos_un_cobro

Por último, se obtuvieron las medidas estadísticas correspondientes de las columnas que se agregarón.

Para las transacciones diarias que hicieron al menos un pago. 
* Media                  1226.93

* Desviación estandar     819.71

* Mínimo                    0.00

* 1° cuartil (25%)        848.50

* 2° cuartil (50%)       1102.00

* 3° cuartil (75%)       1373.00

* Máximo                19089.00

Para las transacciones diarias que hicieron al menos un cobro. 
* Media                  813.05

* Desviación estandar     806.85

* Mínimo                    0.00

* 1° cuartil (25%)        502.50

* 2° cuartil (50%)       608.00

* 3° cuartil (75%)       764.00

* Máximo                 17717.00

In [ ]:
# df_una_transaccion['transacciones_diarias'] = df_una_transaccion['cuentas_que_han_realizado_al_menos_un_pago'].map(lambda x: x - x.shift(1))
df_una_transaccion['transacciones_diarias_al_menos_un_pago'] = df_una_transaccion['cuentas_que_han_realizado_al_menos_un_pago'] - df_una_transaccion['cuentas_que_han_realizado_al_menos_un_pago'].shift(1)
df_una_transaccion.iloc[0,3] = df_una_transaccion.iloc[0,1]
df_una_transaccion['transacciones_diarias_al_menos_un_cobro'] = df_una_transaccion['cuentas_que_han_realizado_al_menos_un_cobro'] - df_una_transaccion['cuentas_que_han_realizado_al_menos_un_cobro'].shift(1)
df_una_transaccion.iloc[0,4] = df_una_transaccion.iloc[0,2]
df_una_transaccion

,fecha,cuentas_que_han_realizado_al_menos_un_pago,cuentas_que_han_realizado_al_menos_un_cobro,transacciones_diarias_al_menos_un_pago,transacciones_diarias_al_menos_un_cobro
0,2019-10-23,19089.0,17717.0,19089.0,17717.0
1,2019-10-24,19706.0,18257.0,617.0,540.0
2,2019-10-25,20905.0,19383.0,1199.0,1126.0
3,2019-10-28,21367.0,19791.0,462.0,408.0
4,2019-10-29,22049.0,20371.0,682.0,580.0
...,...,...,...,...,...
1002,2023-01-12,1229066.0,816604.0,1553.0,477.0
1003,2023-01-13,1231154.0,817316.0,2088.0,712.0
1004,2023-01-14,1232536.0,817836.0,1382.0,520.0
1005,2023-01-15,1233759.0,818252.0,1223.0,416.0
1006,2023-01-16,1235516.0,818737.0,1757.0,485.0

In [ ]:
estadisticos_transacciones_diarias_al_menos_un_pago = round(df_una_transaccion['transacciones_diarias_al_menos_un_pago'].describe(),2)
estadisticos_transacciones_diarias_al_menos_un_pago

count     1007.00
mean      1226.93
std        819.71
min          0.00
25%        848.50
50%       1102.00
75%       1373.00
max      19089.00
Name: transacciones_diarias_al_menos_un_pago, dtype: float64

In [ ]:
estadisticos_transacciones_diarias_al_menos_un_cobro = round(df_una_transaccion['transacciones_diarias_al_menos_un_cobro'].describe(),2)
estadisticos_transacciones_diarias_al_menos_un_cobro

count     1007.00
mean       813.05
std        806.85
min          0.00
25%        502.50
50%        608.00
75%        764.00
max      17717.00
Name: transacciones_diarias_al_menos_un_cobro, dtype: float64